TDL-19326: Add missing integration tests
singer-io/tap-recharge pull request #31
Opened 2022-06-16 09:35 UTC by savan-chovatiya

# Description of change
(write a short description or paste a link to JIRA)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-06-28 11:19 UTC, dbshah1212 approved these changes

2022-07-04 06:56 UTC, harshpatel4crest approved these changes

2022-07-13 17:32 UTC, RushiT0122 requested changes
Requested changes in test_recharge_all_fields.py.

2022-07-14 08:26 UTC, savan-chovatiya commented on tests/test_recharge_all_fields.py
> +            'browser_ip' # Field is not present in API doc at first level
We are not able to generate data for the above fields so added those comments. Also, we don't remove any fields from the schema. We marked some fields with unsupported inclusion in past in the above-mentioned scenarios. Anyway, that's not the case here.

2022-07-15 07:28 UTC, RushiT0122 approved these changes

2022-07-19 21:27 UTC, KrisPersonal approved these changes

2022-07-20 06:52 UTC, merged